include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/base.cmake)

# 裁剪：只保留核心 shaping + FreeType 集成
set(HB_BUILD_SUBSET OFF CACHE BOOL "" FORCE)
set(HB_BUILD_RASTER OFF CACHE BOOL "" FORCE)
set(HB_BUILD_VECTOR OFF CACHE BOOL "" FORCE)
set(HB_BUILD_GPU OFF CACHE BOOL "" FORCE)
set(HB_BUILD_UTILS OFF CACHE BOOL "" FORCE)
set(HB_HAVE_GOBJECT OFF CACHE BOOL "" FORCE)
set(HB_HAVE_ICU OFF CACHE BOOL "" FORCE)
set(HB_HAVE_GLIB OFF CACHE BOOL "" FORCE)
set(HB_HAVE_GRAPHITE2 OFF CACHE BOOL "" FORCE)
set(HB_HAVE_CAIRO OFF CACHE BOOL "" FORCE)
set(HB_HAVE_INTROSPECTION OFF CACHE BOOL "" FORCE)
function(_cppmodule_add_harfbuzz)
    if(HIYUI_INSTALL_SDK)
        set(SKIP_INSTALL_ALL OFF)
        set(SKIP_INSTALL_HEADERS OFF)
        set(SKIP_INSTALL_LIBRARIES OFF)
    else()
        set(SKIP_INSTALL_ALL ON)
    endif()
    cppmodule_add_subdirectory(harfbuzz "${CPPMODULE_ROOTPATH}/harfbuzz")
endfunction()
_cppmodule_add_harfbuzz()

if(EMSCRIPTEN)
    target_compile_definitions(harfbuzz PRIVATE HB_NO_PRAGMA_GCC_DIAGNOSTIC_ERROR)
endif()

if(NOT TARGET cppmodule::harfbuzz)
    add_library(cppmodule::harfbuzz INTERFACE IMPORTED GLOBAL)
    target_link_libraries(cppmodule::harfbuzz INTERFACE harfbuzz)
endif()
