# incbin.cmake - 二进制资源嵌入 CMake 模块 (单文件版)
#
# 用法:
#   include(cmake/incbin.cmake)
#   add_executable(myapp main.cpp)
#   target_link_embed(myapp EMBED_DIR embed)
#
# 平台策略:
#   GCC/Clang/MinGW → .S 汇编 .incbin  (生成+编译 零开销)
#   MSVC            → .c 字符串字面量    (批量正则 快速生成+编译)

# ==============================================================================
# 脚本模式: cmake -P incbin.cmake (MSVC 构建时生成 .c + .h)
# ==============================================================================
if(CMAKE_SCRIPT_MODE_FILE)

    # --- 参数默认值 ---
    if(NOT DEFINED INCBIN_EMBED_DIR)
        set(INCBIN_EMBED_DIR "embed")
    endif()
    if(NOT DEFINED INCBIN_OUTPUT_FILE)
        set(INCBIN_OUTPUT_FILE "embed_data.c")
    endif()
    if(NOT DEFINED INCBIN_HEADER_FILE)
        get_filename_component(_dir "${INCBIN_OUTPUT_FILE}" DIRECTORY)
        get_filename_component(_name "${INCBIN_OUTPUT_FILE}" NAME_WE)
        if(_dir STREQUAL "")
            set(INCBIN_HEADER_FILE "${_name}.h")
        else()
            set(INCBIN_HEADER_FILE "${_dir}/${_name}.h")
        endif()
    endif()
    if(NOT DEFINED INCBIN_SOURCE_DIR)
        set(INCBIN_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/..")
    endif()

    # 将相对路径转为绝对路径
    if(NOT IS_ABSOLUTE "${INCBIN_EMBED_DIR}")
        get_filename_component(INCBIN_EMBED_DIR "${INCBIN_SOURCE_DIR}/${INCBIN_EMBED_DIR}" ABSOLUTE)
    endif()

    # 路径 → 符号名
    function(_incbin_path_to_symbol input_path output_var)
        string(REGEX REPLACE "^[/\\\\]+" "" path "${input_path}")
        string(REGEX REPLACE "[/\\\\]" "_" symbol "${path}")
        string(REGEX REPLACE "\\." "_" symbol "${symbol}")
        string(TOLOWER "${symbol}" symbol)
        set(${output_var} "${symbol}" PARENT_SCOPE)
    endfunction()

    # Header guard
    get_filename_component(_hname "${INCBIN_HEADER_FILE}" NAME)
    string(TOUPPER "${_hname}" _hguard)
    string(REGEX REPLACE "[^A-Z0-9]" "_" _hguard "${_hguard}")
    set(_hguard "INCBIN_${_hguard}")

    # 无文件时生成占位
    if(NOT EXISTS "${INCBIN_EMBED_DIR}")
        message(STATUS "INCBIN: 目录 ${INCBIN_EMBED_DIR} 不存在")
        file(WRITE "${INCBIN_OUTPUT_FILE}" "/* no files */\n")
        file(WRITE "${INCBIN_HEADER_FILE}" "#ifndef ${_hguard}\n#define ${_hguard}\n#endif\n")
        return()
    endif()

    file(GLOB_RECURSE _files LIST_DIRECTORIES false "${INCBIN_EMBED_DIR}/*")
    if(NOT _files)
        message(STATUS "INCBIN: 目录 ${INCBIN_EMBED_DIR} 中没有文件")
        file(WRITE "${INCBIN_OUTPUT_FILE}" "/* no files */\n")
        file(WRITE "${INCBIN_HEADER_FILE}" "#ifndef ${_hguard}\n#define ${_hguard}\n#endif\n")
        return()
    endif()

    # ---- 生成 .c (字符串字面量) ----
    file(WRITE "${INCBIN_OUTPUT_FILE}" "/* Auto-generated by incbin.cmake (MSVC string-literal mode) */\n\n")

    # ---- 生成 .h ----
    file(WRITE "${INCBIN_HEADER_FILE}" "/* Auto-generated by incbin.cmake */\n")
    file(APPEND "${INCBIN_HEADER_FILE}" "#ifndef ${_hguard}\n#define ${_hguard}\n\n")
    file(APPEND "${INCBIN_HEADER_FILE}" "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")

    foreach(fpath IN LISTS _files)
        file(RELATIVE_PATH _rel "${INCBIN_SOURCE_DIR}" "${fpath}")
        _incbin_path_to_symbol("${_rel}" _sym)
        message(STATUS "INCBIN: [MSVC] ${_rel} -> ${_sym}")

        # 读取十六进制
        file(READ "${fpath}" _hex HEX)
        string(LENGTH "${_hex}" _hex_len)
        math(EXPR _fsize "${_hex_len} / 2")

        # 批量转换: "89504e47" → "\x89\x50\x4e\x47"  (一步正则)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "\\\\x\\1" _escaped "${_hex}")

        # 按 16000 字符 (4000 字节) 分段, 避免 MSVC 单字符串字面量长度限制
        string(LENGTH "${_escaped}" _esc_len)
        set(_c_literal "")
        set(_pos 0)
        while(_pos LESS _esc_len)
            math(EXPR _remaining "${_esc_len} - ${_pos}")
            if(_remaining LESS 16000)
                set(_chunk_len ${_remaining})
            else()
                set(_chunk_len 16000)
            endif()
            string(SUBSTRING "${_escaped}" ${_pos} ${_chunk_len} _chunk)
            string(APPEND _c_literal "    \"${_chunk}\"\n")
            math(EXPR _pos "${_pos} + ${_chunk_len}")
        endwhile()

        # .c 数据定义 (字符串字面量末尾自带 \0, sizeof = 实际大小 + 1)
        file(APPEND "${INCBIN_OUTPUT_FILE}" "/* ${_rel} (${_fsize} bytes) */\n")
        file(APPEND "${INCBIN_OUTPUT_FILE}" "__declspec(align(16)) const unsigned char ${_sym}_data[] =\n${_c_literal};\n")
        file(APPEND "${INCBIN_OUTPUT_FILE}" "const unsigned int ${_sym}_size = sizeof(${_sym}_data) - 1;\n\n")

        # .h 声明
        file(APPEND "${INCBIN_HEADER_FILE}" "/* ${_rel} (${_fsize} bytes) */\n")
        file(APPEND "${INCBIN_HEADER_FILE}" "extern const unsigned char ${_sym}_data[];\n")
        file(APPEND "${INCBIN_HEADER_FILE}" "extern const unsigned int ${_sym}_size;\n\n")
    endforeach()

    file(APPEND "${INCBIN_HEADER_FILE}" "#ifdef __cplusplus\n}\n#endif\n\n")
    file(APPEND "${INCBIN_HEADER_FILE}" "#endif /* ${_hguard} */\n")

    message(STATUS "INCBIN: 已生成 ${INCBIN_OUTPUT_FILE}")
    message(STATUS "INCBIN: 已生成 ${INCBIN_HEADER_FILE}")
    return()
endif()

# ==============================================================================
# 模块模式: include(cmake/incbin.cmake)
# ==============================================================================
include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/base.cmake)

if(NOT TARGET cppmodule::incbin)
    add_library(cppmodule::incbin INTERFACE IMPORTED GLOBAL)
    target_include_directories(cppmodule::incbin INTERFACE
        "${CPPMODULE_ROOTPATH}/incbin"
    )
endif()

# 非 MSVC 启用汇编语言
if(NOT MSVC)
    enable_language(ASM)
endif()

# 默认嵌入目录
if(NOT DEFINED INCBIN_EMBED_DIR)
    set(INCBIN_EMBED_DIR "embed" CACHE PATH "Directory containing files to embed")
endif()

# 路径 → 符号名 (模块作用域)
function(_incbin_path_to_symbol input_path output_var)
    string(REGEX REPLACE "^[/\\\\]+" "" path "${input_path}")
    string(REGEX REPLACE "[/\\\\]" "_" symbol "${path}")
    string(REGEX REPLACE "\\." "_" symbol "${symbol}")
    string(TOLOWER "${symbol}" symbol)
    set(${output_var} "${symbol}" PARENT_SCOPE)
endfunction()

# ==============================================================================
# target_link_embed(<target> [EMBED_DIR <dir>])
# ==============================================================================
function(target_link_embed target)
    cmake_parse_arguments(_ARG "" "EMBED_DIR" "" ${ARGN})

    # 解析嵌入目录
    if(DEFINED _ARG_EMBED_DIR)
        set(_embed_dir "${_ARG_EMBED_DIR}")
    else()
        set(_embed_dir "${INCBIN_EMBED_DIR}")
    endif()
    if(NOT IS_ABSOLUTE "${_embed_dir}")
        set(_embed_dir "${CMAKE_SOURCE_DIR}/${_embed_dir}")
    endif()

    # 收集嵌入文件
    file(GLOB_RECURSE _embed_files CONFIGURE_DEPENDS LIST_DIRECTORIES false "${_embed_dir}/*")
    if(NOT _embed_files)
        message(WARNING "INCBIN: ${_embed_dir} 中没有文件")
        return()
    endif()

    # 每个 target 独立的输出目录
    set(_out_dir "${CMAKE_BINARY_DIR}/embed_incbin/${target}")
    file(MAKE_DIRECTORY "${_out_dir}")

    set(_header "${_out_dir}/embed_data.h")
    set(_incbin_script "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/incbin.cmake")
    set(_lib "${target}_embed_data")

    if(MSVC)
        # ==================================================================
        # MSVC: 构建时 cmake -P 生成 .c (字符串字面量)
        # ==================================================================
        set(_source "${_out_dir}/embed_data.c")

        add_custom_command(
            OUTPUT "${_source}" "${_header}"
            COMMAND ${CMAKE_COMMAND}
                -DINCBIN_EMBED_DIR=${_embed_dir}
                -DINCBIN_OUTPUT_FILE=${_source}
                -DINCBIN_HEADER_FILE=${_header}
                -DINCBIN_SOURCE_DIR=${CMAKE_SOURCE_DIR}
                -P "${_incbin_script}"
            DEPENDS ${_embed_files} "${_incbin_script}"
            WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
            COMMENT "INCBIN: [MSVC] 生成 ${target} 嵌入数据"
        )

        add_library(${_lib} STATIC "${_source}")

    else()
        # ==================================================================
        # GCC/Clang/MinGW: 配置时生成 .S (汇编 .incbin)
        # ==================================================================
        set(_source "${_out_dir}/embed_data.S")
        set(_hguard "INCBIN_EMBED_DATA_H_${target}")
        string(TOUPPER "${_hguard}" _hguard)
        string(REGEX REPLACE "[^A-Z0-9]" "_" _hguard "${_hguard}")

        # ---- .S 汇编 ----
        set(_asm "/* Auto-generated by incbin.cmake — DO NOT EDIT */\n\n")

        # 平台抽象宏 (通过 C 预处理器, .S 文件自动经过 cpp)
        string(APPEND _asm "#if defined(__APPLE__)\n")
        string(APPEND _asm "#  define INCBIN_SECTION   .section __DATA,__const\n")
        string(APPEND _asm "#  define INCBIN_GLOBAL(s) .globl _##s\n")
        string(APPEND _asm "#  define INCBIN_LABEL(s)  _##s\n")
        string(APPEND _asm "#  define INCBIN_ALIGN     .p2align 4\n")
        string(APPEND _asm "#elif defined(_WIN32)\n")
        string(APPEND _asm "#  define INCBIN_SECTION   .section .rdata,\"dr\"\n")
        string(APPEND _asm "#  define INCBIN_GLOBAL(s) .globl s\n")
        string(APPEND _asm "#  define INCBIN_LABEL(s)  s\n")
        string(APPEND _asm "#  define INCBIN_ALIGN     .balign 16\n")
        string(APPEND _asm "#else\n")
        string(APPEND _asm "#  define INCBIN_SECTION   .section .rodata\n")
        string(APPEND _asm "#  define INCBIN_GLOBAL(s) .global s\n")
        string(APPEND _asm "#  define INCBIN_LABEL(s)  s\n")
        string(APPEND _asm "#  define INCBIN_ALIGN     .balign 16\n")
        string(APPEND _asm "#endif\n\n")

        # ---- .h 头文件 ----
        set(_h "/* Auto-generated by incbin.cmake */\n")
        string(APPEND _h "#ifndef ${_hguard}\n#define ${_hguard}\n\n")
        string(APPEND _h "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")

        foreach(_fpath IN LISTS _embed_files)
            file(RELATIVE_PATH _rel "${CMAKE_SOURCE_DIR}" "${_fpath}")
            _incbin_path_to_symbol("${_rel}" _sym)

            # 绝对路径, 正斜杠
            file(TO_CMAKE_PATH "${_fpath}" _abs_fwd)

            message(STATUS "INCBIN: [ASM] ${_rel} -> ${_sym}")

            # .S : data
            string(APPEND _asm "/* ${_rel} */\n")
            string(APPEND _asm "INCBIN_SECTION\n")
            string(APPEND _asm "INCBIN_GLOBAL(${_sym}_data)\n")
            string(APPEND _asm "INCBIN_ALIGN\n")
            string(APPEND _asm "INCBIN_LABEL(${_sym}_data):\n")
            string(APPEND _asm "    .incbin \"${_abs_fwd}\"\n")
            string(APPEND _asm "_incbin_end_${_sym}:\n\n")

            # .S : size
            string(APPEND _asm "INCBIN_GLOBAL(${_sym}_size)\n")
            string(APPEND _asm "INCBIN_ALIGN\n")
            string(APPEND _asm "INCBIN_LABEL(${_sym}_size):\n")
            string(APPEND _asm "    .long _incbin_end_${_sym} - INCBIN_LABEL(${_sym}_data)\n\n")

            # .h
            string(APPEND _h "/* ${_rel} (embedded) */\n")
            string(APPEND _h "extern const unsigned char ${_sym}_data[];\n")
            string(APPEND _h "extern const unsigned int ${_sym}_size;\n\n")
        endforeach()

        # .h 结尾
        string(APPEND _h "#ifdef __cplusplus\n}\n#endif\n\n")
        string(APPEND _h "#endif /* ${_hguard} */\n")

        # 写入文件
        file(WRITE "${_source}" "${_asm}")
        file(WRITE "${_header}" "${_h}")

        add_library(${_lib} STATIC "${_source}")

        # 嵌入文件变更时重新汇编 .S
        set_source_files_properties("${_source}" PROPERTIES
            OBJECT_DEPENDS "${_embed_files}"
        )
    endif()

    # ---- 通用: 链接 & 包含 ----
    target_link_libraries(${target} PRIVATE ${_lib})
    target_include_directories(${target} PRIVATE "${_out_dir}")

    message(STATUS "INCBIN: 已配置 ${target}")
    message(STATUS "  - 嵌入目录: ${_embed_dir}")
    message(STATUS "  - 输出目录: ${_out_dir}")
endfunction()
