include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/base.cmake)

if(NOT TARGET sndfile)
    if (MSVC)
        unset(CMAKE_MSVC_RUNTIME_LIBRARY CACHE)
        set(ENABLE_STATIC_RUNTIME ON)
    else ()
        set(ENABLE_STATIC_RUNTIME ON)
    endif ()
    set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(BUILD_REGTEST OFF CACHE BOOL "" FORCE)
    set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
    set(ENABLE_PACKAGE_CONFIG OFF CACHE BOOL "" FORCE)
    
    cppmodule_add_subdirectory(libsndfile "${CPPMODULE_ROOTPATH}/libsndfile")
endif()

if(NOT TARGET cppmodule::sndfile)
    add_library(cppmodule::sndfile INTERFACE IMPORTED GLOBAL)
    target_include_directories(cppmodule::sndfile INTERFACE ${CPPMODULE_ROOTPATH}/libsndfile/include)
    target_link_libraries(cppmodule::sndfile INTERFACE sndfile)
endif()
